### ISSUE TITLE
modified_after and cursor broken

### ISSUE THREAD

**Issue by KoalaBear84** [alexschneider/pushbullet-js#6]
They do not work after converted from GET parameters to JSON. When I do a request with a cursor, I get the same 500 pushes back, not the next 'page' of cursors.

It currently does not work with JSON as parameters. I can't find anything about this 'problem' combined with REST. I only found this

https://pusher.com/docs/rest_api

Parameters MUST be submitted in the query string for GET requests. For POST requests, parameters MAY be submitted in the query string, but SHOULD be submitted in the POST body as a JSON hash (while setting Content-Type: application/json).

**Comment by alexschneider** [comment]
You're right, of course, I'm not sure what I was thinking last night. The latest commit SHOULD fix it, but I'm unable to test anything right now. 

One of these days, I've got to set up a testing suite like QUnit or Mocha.

**Comment by KoalaBear84** [comment]
It works :)

Also a better solution as I checked it. Only documentation is reverted I guess? :)

**Comment by alexschneider** [comment]
I'll update the documentation at some point in time when I have more time.
